pptp:
	gcc -O2 pptp_compile/*.c pptp_compile/tommyds/tommy.c -o test -lpcap

quic:
	gcc -O2 quic_compile/*.c quic_compile/tommyds/tommy.c -o test -lpcap

ip_tcp:
	gcc -O2 ip_tcp_compile/*.c ip_tcp_compile/tommyds/tommy.c -o test -lpcap

gtp:
	gcc -O2 gtp_compile/*.c gtp_compile/tommyds/tommy.c -o test -lpcap

clean:
	rm test